---
title: "Basic Visualization"
author: "Sumad Singh"
date: "September 7, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## BASIC GRAPHIC SYSTEM IN R
### PARAMETERS TO ANNOTATE GRAPHS
### COMBINE GRAPHS

```{r}
## USING BASIC GRAPHIC SYSTEM IN R
#1.LAYERING 
#We want to build layers of plots on a single chart, R provides a system to do that
#help("dev.cur")
# IDEA IS TO OPEN A GRAPHICS DEVICE, R ALLOWS TO OPEN MULTIPLE DEVICES,
# DIRECT OUTPUT TO A CHOICE OF DEVICE
# FUNCTIONS LIKE PDF(), PNG(), JPEG() OPEN A DEVICE BY THEMSELVES
# HIGH LEVEL FUNCTIONS LIKE PLOT(), HIST() ETC ALSO OPEN A DEVICE

# USEFUL FUNCTIONS FOR OPENING AND MANAGING DEVICES
# a Null device is always open in a session, once a new device is opened Null does not show up
#dev.new() # Open a new device, 
# dev.cur() # lists the name and number of current active device
# dev.list() # lists the names and mumbers of all open devices
# dev.off() # shuts off a device
# dev.next() # shuffle to next device w.r.t the current
# dev.previous() # same, goes to previous
# graphics.off()  # closes all open devices

# EXAMPLE OF PLOTTING A SCATTER PLOT, AND A REGRESSION LINE
attach(mtcars)
dev.new()
plot(x = hp ,y = mpg,type = "p") # PLOT IS A HIGH LEVEL FUNCTION IN R, WHICH CAN MAKE DIFFERENT TYPE OF PLOTS
# BASED ON THE 'TYPE' ARGUMENT
abline(reg = lm(mpg~hp))
detach(mtcars)
#help(abline)

```

```{r}
#2. KEY PLOTTING FUNCTIONS
# A. PLOT
#PLOT FUNCTION WORKS DIFFERENTY ON OBJECTS LIKE DATA FRAMES, DENSITY, PLOT.DEFAULT WORKS 
#FOR SCATTERPLOT B/W X AND Y
attach(mtcars)
plot(x= hp, y= mpg,type = "p",xlab = "log (horsepower)",ylab = "log(Miles per gallon)",log = "xy" ,main = " Log Linear relationship?"  ,
     sub =  "log mpg vs log hp" ,frame.plot = TRUE,asp = 1)

detach(mtcars)
# xlim, ylim are limits on the axes
# main title
# sub - subtitle of the plot
# xlab/ylab -  x , y axis labels
# axes - used "xaxt" or "yaxt to suppresss one of thre axes"
# frame.plot - logical to choose if plot to be enclosed in a box
# asp - aspect ration i.e y/x

```
```{r}
# Plot function operates on a data frame with all numeric columns to give
# bivariate scatter plots
plot(mtcars)
```
```{r}
#3. GRAPHICAL PARAMETERS - COLOR, LINE/POINT/BAR TYPE, LENGTH,WIDTH ,TEXT ETC
#A. GENERAL FUNCTION TO SPECIFY GRAPHICAL PARAMETERS
#par() # return a list of current graphical paramters
par.default <- par(no.readonly = TRUE) # return the current setting of parameters that can be modified, use of no.readonly=T
par(lty = 2, lwd = 2, pch= 2 ,cex= 1.2) # new settings
attach(mtcars)
plot(x= hp, y= mpg,type = "p",xlab = "horsepower",ylab = "Miles per gallon" ,main = " Linear relationship?"  ,
     sub =  "mpg vs hp" ,frame.plot = TRUE)
abline(reg = lm(mpg ~ hp))
detach(mtcars)
par(par.default) # return to original settings


#B. GRAPHICAL PARAMETERS WITHIN HIGH LEVEL FUNCTIONS (NOT ALL ARE AVAILABLE THOUGH!, 
#SO USE A OPTION AS NEEDED )
# plot() and abline() for example have ... argument to specify graphical parameters,
# these settings are used only for the current plot
```

```{r}
#C.  PARAMETERS FOR POINT AND LINES
# pch -  point type, goes from 0 to 24
# cex - size zooming relative to default of 1, expressed as 1.<x>
# lty - line type goes from 1 to 6
# lwd - line width ,elative to default of 1, expressed as 1.<x>

# D. PARAMETERS FOR COLORS
# col - color of lines or points in the plot, can be given as a vector, the values of which are recycled
# col.axis - color of axes
# col.lab - color of label of axes
# col.main , col.sub 
#fg, bg - foreground and background color

colors()
rainbow(10)
```

