---
title: "RIA Ch1 "
output: github_document
---
## SEARCHING IN R
---
```{r} 
options(echo=FALSE, eval = FALSE)
# GETTING HELP
# help.start()
# GET Amazing links that include
#1. An introduction to R from CRAN  -- VERY VALUABLE RESOURCE
#2.A Search Engine 
#3. User Manuals, Technical Papers
#4. Mailing lists by SIGs (Special Interest Groups)
# 5. list out of packages and so on..

#The R Studio home also offer a lot of useful information -
 # 1. R Cheat Sheets for R Studio packages. 
 #  2. Learning R Online etc
 
#RSiteSearch("probability distributions")
# The power of searching on Rsite is that it gives a full view of tasks list 
#where the referecnes could be found.
# Instead of a google search, this is more relevant. One can see functions, 
#packages, NEWS, if the packages has
#vignettes to refer to etc.

data()
# Gives summary of data sets of all loaded packages, can make it specific by giving 
# packagename as an argument

vignette()

# Gives the vignettes of all available loaded packages in the session. Example of data.table - 
# datatable-reshape                Efficient reshaping using data.tables (source, html)
# datatable-faq                    Frequently asked questions (source, html)
# datatable-intro                  Introduction to data.table (source, html)
# datatable-keys-fast-subset       Keys and fast binary search based subset (source, html)
# datatable-reference-semantics    Reference semantics (source, html)
# datatable-secondary-indices-and-auto-indexing
#                                  Secondary indices and auto indexing (source, html)
                                 
#vignette("datatable-intro")  

#apropos("poisson",mode = "function")
# Lets you do a string search and return functions that have the string name
```

## HANDLING WORKSPACE
---
```{r}
# REMOVE  OBJECTS by passing them to argument list
rm(list = ls())
# GLOBAL OPTIONS, and setting an option
help("options")
# SAVING AND RETREIVING COMMAND HISTORY :Get a hitory of commands typed on command line
#history(max.show = 25) 
#savehistory() # used to save history of commands, the default file where command history 
#is saved is .Rhistory
#loadhistory()
# SAVING WORKSPACE and LOADING WORKSPACES
#save.image() # Used to save the workspace i.e packages loaded, objects created etc. The default file saved to
#is .RData
#load()


```

---
## CONNECTIONS AND REDIRECTING OUTPUT
```{r}
# DIRECTORY OPERATIONS
# Create a directory and assign permissions using 4 digits like "0777"
#dir.create(path= , mode = )
#dir.exists()

# FILE PATH 
# faster than paste, and do not need to specify separators
#file.path()

# CONNECTION TO A FILE

# con <- file(description = ,open = ,) giving a file name and one of the common modes i.e "r" , "w" ,"a" opens as well as

# DIRECTING TEXT OUPTPUT
#sink(file =, append =,split = ,type =  ) directs text output to a connection as well stops, either append or overwrite
# These connections are open with every R session - stdout, stderr.
#message(), warning(), stop() send output to stderr(). sink(type= "output") directs output from stdout() to a connection 
#you open or sink(type= "message") diverts output from stderr()
sink(file = "test.log" , append = "true",type = "output") # sink also opens a connection 
cat("test if log file is creted","\n")
sink()

# OPENING CONNECTION TO GRAPHICS DEVICES
# pdf(), jpeg(), png() open the connection 
# dev.off() closes the connection

```

## PACKAGES
```{r}
# BASE PACKAGES
# The install comes with base packages 
options()$defaultPackages
# "datasets"  "utils"     "grDevices" "graphics"  "stats"     "methods" 

# NEW PACKAGES
# Use install.packages()
# Choose cran mirror

# LIBRARY WITH PACKAGES
# The path of library/ies in use is listed as
.libPaths()
# Packages saved in the library are listed with
library()

# update.packages() Updated package 


# LOADED/ATTACHED PACKAGES
search()

# LEARNING ABOUT A PACKAGE
help(package = stats) # lists out all the functions in the package
data(package= "car") # summary of all dats sets in the package

```

## CUSTOMIZING START UP ENVIRONMENT
```{r}
# ENVIRONMENT VARIABLES
# R_HOME = Default home where R's installation resides
# HOME - Default home directory of thre user
# List of Environment variables is given by Sys.getenv()

# Behavior of R on start up is given in detail in 'Introduction to R'. Use  help(Startup) 
# Rprofile.site - When R session starts, this file, if exists is executed from R_HOME/etc location
# .Rprofile - This file is executed from getwd() , if not found  then looked at HOME/

# Check if the file exists
file.exists(file.path(Sys.getenv("R_HOME"),"etc",".Rprofile"))

# .FIRST() and .LAST()
# Functions that can be created in any of these files, that are executed at the start and at the end of session resp.

# Summary of uses
# Load packages at start, clean up objects at the end, or save command history
# Create shortcuts for use of some commands
# Load often used user defined functions, by sourcing a file with those functions
# Setting up some global options with prefered values
# Setting up a custom library path

```

## NOINTERACTIVE MODE OR BATCH MODE
```{r}
# COMMAND structure 
# R CMD BATCH <options> infile outfile
# infile - an executable file .R
# outfile - where utputs go , a .Rout extension file

# OPTIONS
# optparse() is a package usefule to pass command line variables
# Section command lne options in 'CRAN's Introduction to R' has more details on available options
```

## USING OUTPUTS AS INPUT
```{r}
help(mtcars)
str(mtcars)
model <- lm( formula = mpg ~ ., data = mtcars)
# Model is the output, we can use it as an input with some function

```

```{r}
summary(model)
```
```{r}
# Diagnostic plots using plot() on the model object
plot(model)
```
```{r}
cooks.distance(model = model)
```


```{r}
plot(cooks.distance(model))
```
```{r}
#help(lm) - will come to get to the implemenation details later on lm
```

## BIGDATESETS
```{r}
# Memory related problem can come up in form of errors like 
# IN-MEMORY OPERATIONS
#1. EFFICIENT PROGRAMMING
# Some of the good practices are -
#a. Clean up memory by removing large objects in the memory
#b. Use functions that perform vectorized operations like apply() family instead of loops
#c. Profile function for time, use sys.time(), Rprofile()

#2. SAVING DATASETS EXTERNALLY
#3. USING MORE EFFICIENT IMPLEMENTATIONS OF STATISTICAL ALGORITHMS
```


